### ISSUE TITLE
Working with older versions of node?

### ISSUE THREAD

**Issue by AnalogJ** [claygregory/serverless-prune-plugin#1]
Hey,
This plugin was working perfectly with nodejs 6.x and 7.x
But when I went back to 4.3, I get the following error:

```
sls prune -n 4
 
  Syntax Error -------------------------------------------
 
     Unexpected token [
```

Which I think is due to the following line: 
https://github.com/claygregory/serverless-prune-plugin/blob/master/index.js#L57

Any chance you could modify the `.each` block to be backwards compatible?

Since you're using Travis, you could also add a few older versions to your [.travis.yml](https://github.com/claygregory/serverless-prune-plugin/blob/master/.travis.yml#L3) file. Maybe test the same versions that the [serverless](https://github.com/serverless/serverless/blob/master/.travis.yml#L3) project does?

Thanks!

**Comment by claygregory** [comment]
Good call — discovered a few places I was using ES6 syntax, breaking older versions of Node. I ended up using latest 4, 5, 6 in .travis.yml, simply because I don't trust myself to continually monitor and stay up to date with exact versions used by Serverless.

Anyway, this should be fixed on release 1.0.4 — thanks!
