### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by jebricker** [claygregory/serverless-prune-plugin#43]
Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - Prune for "number", "stage", "region", "function", "layer", "includeLayers", "dryRun"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error

Framework Core: 2.72.2 (local)
Plugin: 5.5.4
SDK: 4.3.0
Components: 3.18.2

**Comment by shadowhand** [comment]
This is marked as completed, but a new release has not been made with the fixed version.

**Comment by claygregory** [comment]
Hi @shadowhand — that's because this was [one](https://github.com/claygregory/serverless-prune-plugin/issues/42) of [several](https://github.com/claygregory/serverless-prune-plugin/issues/34) [duplicates](https://github.com/claygregory/serverless-prune-plugin/issues/29) of an issue that has been closed since [version 1.5.0](https://github.com/claygregory/serverless-prune-plugin/releases/tag/v.1.5.0). Please update to any later plugin version to resolve.
