### ISSUE TITLE
Pruning incorrectly

### ISSUE THREAD

**Issue by MatheusVellone** [claygregory/serverless-prune-plugin#6]
First, thanks for the amazing plugin!

I've installed it in my project and run the `sls prune -s prod -n 10`.
Most of my project lambdas had 240 versions, and I thought it would remove 230 of them, keeping only the newest 10. But instead, it removed the oldest ~10~ 40, and kept 200 most recent ones.

The docs on README says the following
> This will delete all but the n-most recent versions of each function deployed. Versions referenced by an alias are automatically preserved.

**Comment by MatheusVellone** [comment]
Here's the output I get for one of the lambdas:
> Serverless: Prune: xxxxx has 49 versions published and 0 aliases, 39 versions selected for deletion
Serverless: Prune: Deleting xxxxx v84...
Serverless: Prune: Deleting xxxxx v83...
...
Serverless: Prune: Deleting xxxxx v48...
Serverless: Prune: Pruning complete

Then I run it again, just to check and:
> Serverless: Prune: Querying for deployed versions
Serverless: Prune: xxxxx has 49 versions published and 0 aliases, 39 versions selected for deletion
Serverless: Prune: Deleting xxxxx v124...
Serverless: Prune: Deleting xxxxx v123...
Serverless: Prune: Deleting xxxxx v122...
(Then I stopped the execution)

It says I have 49 versions, but I have far more versions then 49
Looks like it reads only 50 (or 49) versions of a function, then it keeps only the newest `n` (10 in my case).
But the function doesn't have "only" 50 versions. I'll run the command a couple of times and check it.
If I confirm this is the cause, I'll try to work on a PR to fix it.

**Comment by MatheusVellone** [comment]
Confirmed it was reading only ~50 versions. Run it a couple of times and it kept only the first 10 versions.
Don't know if this is intended, but at the end the plugin works as expected.

I'll close the issue because this is no longer exactly a problem.

**Comment by claygregory** [comment]
Thanks for raising this issue. You're correct, the AWS API returns a paged-response of 50 versions/page. The plugin currently only retrieves the first page of results, so on first-use, multiple passes are necessary to winnow away the backlog. When configured on a new project (or on subsequent runs), this isn't a concern since all versions are returned within a single page.

I'm going to re-open this issue and plan to address it soon. Current behavior is less than ideal, and certainly unclear. I'm going to add a note in the readme on existing behavior right now, and will plan to add paging support to the version query in the next week or two.

**Comment by claygregory** [comment]
Hi Matheus — I've addressed this and released in v1.2.0. Thanks again for raising the concern!
